import nexmo
from pprint import pprint

client = nexmo.Client(
  application_id='e6f960ee-334c-43be-a97b-2f81d2d67d5b',
  private_key='./private.key',
)

ncco = [
{
'action': 'talk',
'voiceName': 'Salli',
'text': "Hey Pranavi, This a automatic call generated by sandeep. Wake up at 9 am you have digital circuit design class. thank you. bye"
}
]
response = client.create_call({
'to': [{
'type': 'phone',
'number': '919491263795'
}],
'from': {
'type': 'phone',
'number': '919492671016'
},
'ncco': ncco
})

pprint(response)
