import nexmo
from pprint import pprint

client = nexmo.Client(
  application_id='e6f960ee-334c-43be-a97b-2f81d2d67d5b',
  private_key='./private.key',
)

ncco = [
{
'action': 'talk',
'voiceName': 'Brian',
'text': "Hey Abhinav . Abhinav why are you not studying for exam? . Your madam is informed that you are not studying for exam. This is automatic call generated by Sai Sandeep. Call Sandeep.  bye"
}
]
response = client.create_call({
'to': [{
'type': 'phone',
'number': '917904524327'
}],
'from': {
'type': 'phone',
'number': '919492671016'
},
'ncco': ncco
})

pprint(response)
